version: '3.7'
services:
    horrea:
        build:
            context: .
            dockerfile: ./prod/horrea/Dockerfile
        env_file:
            - ./.env
        ports:
            - ${HORREA_PORT}:${HORREA_PORT}
    caesar:
        build:
            context: .
            dockerfile: ./prod/caesar/Dockerfile
        env_file:
            - ./.env
        ports:
            - ${CAESAR_PORT}:${CAESAR_PORT}
    iudex:
        build:
            context: .
            dockerfile: ./prod/iudex/Dockerfile
        env_file:
            - ./.env
        ports:
            - ${IUDEX_PORT}:${IUDEX_PORT}
    fora:
        build:
            context: .
            dockerfile: ./prod/fora/Dockerfile
        env_file:
            - ./.env
        ports:
            - ${FORA_PORT}:${FORA_PORT}
    fabricae:
        build:
            context: .
            dockerfile: ./prod/fabricae/Dockerfile
        env_file:
            - ./.env
        ports:
            - ${FABRICAE_PORT}:${FABRICAE_PORT}
    senator:
        build:
            context: .
            dockerfile: ./prod/senator/Dockerfile
        env_file:
            - ./.env
        ports:
            - ${SENATOR_PORT}:${SENATOR_PORT}
